# Generated by Django 3.2.25 on 2024-05-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_merge_20240318_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audit_status',
            field=models.CharField(blank=True, default='0', help_text='0=Not Audited; 1=Audited', max_length=16, null=True, verbose_name='audit status'),
        ),
    ]
