# Generated by Django 3.2.25 on 2024-05-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='audit_status',
            field=models.CharField(blank=True, default='0', help_text='0=Not Audited; 1=Audited', max_length=16, null=True, verbose_name='audit status'),
        ),
    ]
